:website:
  :id: "http://merit-intl.com"
  :title: "MErit International"
  :description: "Wholesaler of Model Kits and Figures"
  :hostname: "merit-intl.com"
  :domain: "merit-intl.com"
  :root_url: "http://merit-intl.com"